config/routes.rb
Rails.application.routes.draw do

  resources :friendships
  resources :pets
  resources :users
  resources :store, only: [:index, :new, :create, :show]

  root to:'static#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post "/friendly_interactions/:id", to: "friendship_interactions#create", as: 'new_friendship_interaction'
  post '/owner_interactions/:id', to: 'owner_interactions#create'
  post '/store/:id', to: 'store#create'

  get '/admin', to: 'admins#new'
  post '/admins', to: 'admins#create'
  get '/admins', to: 'admins#index', as: 'admins_homepage'
  get '/analytics', to: 'analytics#index'
  resources :items
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :owner, :class_name => 'User'
  has_many :friendships
  has_many :people_friends, through: :friendships, source: :user
  has_many :pet_items
  has_many :items, through: :pet_items
  validates :name, presence: :true
  before_save :check_mood_level

  def is_happy?
    if mood_level >= 15
      "😾"
    elsif mood_level >= 10
      "😻"
    elsif mood_level >= 7
      "😸"
    elsif mood_level <= 3
      "😿"
    else
      "🐱"
    end
  end

  def self.needs_love
    self.where(mood_level: [0..6]).shuffle.first
  end

  def self.new_cat
    self.order(created_at: :desc).first
  end

  def self.surprise_cat
    self.order(created_at: :asc).shuffle.first
    #self.limit(1).order("RANDOM()")
  end

    #analytics  
  def self.happiest_cats
    self.where(mood_level: [10..15]).pluck(:name, :mood_level)
  end

  ###Methods for Heroku Rake task to decrease pet mood level

  ###this is the rake task
  def self.update_mood_level
    Pet.where("mood_level > ?", 0).update_all("mood_level = mood_level - 1")
  end

  def all_friendships
    self.friendships
  end

  def all_friendship_interactions_ids
  all_friendships.collect do |friendship|
      friendship.friendship_interactions.pluck(:id)
    end.flatten
  end

  def three_most_recent_interactions
    FriendshipInteraction.where(id: all_friendship_interactions_ids).select('kind, created_at, id').order(created_at: :desc).limit(3)
      # all_friendship_interactions[0].select("kind, created_at").order(created_at: :desc).limit(3)
  end

  def array_of_interaction_times
    three_most_recent_interactions.pluck(:created_at)
  end

  def convert_time
    array_of_interaction_times.collect do |time|
      time.strftime("%b %d, %I:%M:%p")
    end
  end

  def extract_kind
    three_most_recent_interactions.pluck(:kind)
  end

  def kind_conversion_for_display
    extract_kind.each do |kind|
      kind.gsub!("play","played with")
      kind.gsub!("scratch", "scratched at")
    end
  end

  def kind_and_time_array
    kind_conversion_for_display.zip(convert_time)
  end

  def check_mood_level
    if self.mood_level > 15
        self.mood_level = 15
    elsif self.mood_level < 0
        self.mood_level = 0
    end
  end


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    if !current_user.nil?
      @pets = Pet.all
      @new_cat = Pet.new_cat
      @needs_love = Pet.needs_love
      @surprise_cat = Pet.surprise_cat
    else
      redirect_to '/login'
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.owner = User.find(current_user)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new
    end
  end

  def show
    if authorize_user
    else
      set_pet
      @user = User.find(current_user)
      @people_friends = @pet.people_friends
    end
  end
  
  def update
    set_pet
    @pet.people_friends << User.find(current_user)
    redirect_to @pet
  end

  private

  def pet_params
    params.require(:pet).permit(:name)
  end
end

app/views/pets/index.html.erb
<body class='pets-index'>
  <section class='pets-list'>
    <h1>KITTY CITY EMPIRE</h1>
    <ol>
      <% @pets.each do |p| %>
       <li><%= link_to p.name, p %></li>
      <% end %>
    </ol>
  </section>

  <section class='pets-visit'>
    <h2>Visit these pretty kitties!</h2>
    new cat on the block: <%= link_to @new_cat.name, @new_cat %><br>
    pet me, purrrrease: <%= link_to @needs_love.name, @needs_love %><br>
    super surprise: <%= link_to @surprise_cat.name, @surprise_cat %>
  </section>
</body>

app/views/pets/new.html.erb
<section class="signup">

  <h1>Create Pet Profile</h1>

  <%= form_for @pet do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
  <% end %>

</section>

app/views/pets/show.html.erb
<body class="pet">
  <section class="pet-profile">
    <h1><%= @pet.name %></h1>
    <h3>Mood Level: <%= @pet.mood_level %></h3>
    <div id="catmogi"><%= @pet.is_happy? %></div>
    All my treats!!<br>
    <h2><% @pet.items.each do |i| %>
      <%= i.emoji %>
    <% end %></h2>
  </section>

  <section class="owner-interactions">
    <% if check_owner_of_pet(@pet) %>
      Hi Owner.
      <%= form_tag("/owner_interactions/#{@pet.id}", method: "post") do %>
        <%= hidden_field_tag(:kind, :scratch) %>
        <%= submit_tag "Pet me" %>
      <%end%>

      <%= form_tag("/owner_interactions/#{@pet.id}", method: "post") do %>
        <%= hidden_field_tag(:kind, :feed) %>
        <%= submit_tag "Feed Me" %>
      <%end%>

      <%= form_tag("/owner_interactions/#{@pet.id}", method: "post") do %>
        <%= hidden_field_tag(:kind, :lick) %>
        <%= submit_tag "Lick Me" %>
      <%end%>

      <%= link_to "Let's go shopping!", store_index_path %><br><br>

      <% if flash[:notice] %>
        <p><%=flash[:notice]%></p>
      <% end %>
    <% end %>
  </section>

  <section class="pet-human-friends">
    All My Friends:
    <ul>
      <% @people_friends.each do |pf| %>
        <li><%= link_to pf.name, pf %></li>
      <% end %>
    </ul>
    <br>

    <% unless is_friend_or_owner_of_pet?(@people_friends, @pet) %>
      <%= button_to "Be My FRIEND!!!", @pet, method: :patch %>
    <% end %>

    <% if check_friend_of_pet(@people_friends) %>
      Hi, <%= @user.name %>, we are best friends!
      <%= form_tag("/friendly_interactions/#{@pet.id}", method: "post") do %>
        <%= hidden_field_tag(:kind, :scratch) %>
        <%= submit_tag "Pet me" %>
      <%end%>
      <%= form_tag("/friendly_interactions/#{@pet.id}", method: "post") do %>
        <%= hidden_field_tag(:kind, :play) %>
        <%= submit_tag "Play with me" %>
      <% end %>
      <% if flash[:notice] %>
        <p><%=flash[:notice]%></p>
      <% end %>
    <% end %>
  </section>

  <section class="caramels-display">
    <% if @user.caramel_points > 0 %>
      <%= @user.name %>'s caramel points: <br>
      <% @user.caramel_points.times do %>
        <div class="candy">🍭</div>
      <% end %>
    <% end %>
  </section>
</body>