config/routes.rb
Rails.application.routes.draw do

  resources :friendships
  resources :pets
  resources :users
  resources :store, only: [:index, :new, :create, :show]

  root to:'static#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  post "/friendly_interactions/:id", to: "friendship_interactions#create", as: 'new_friendship_interaction'
  post '/owner_interactions/:id', to: 'owner_interactions#create'
  post '/store/:id', to: 'store#create'

  get '/admin', to: 'admins#new'
  post '/admins', to: 'admins#create'
  get '/admins', to: 'admins#index', as: 'admins_homepage'
  get '/analytics', to: 'analytics#index'
  resources :items
end

app/models/user.rb
class User < ApplicationRecord
  has_one :pet, :foreign_key => 'owner_id'
  has_many :friendships
  has_many :pet_friends, through: :friendships, source: :pet
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true
  has_many :owner_interactions

#analytics
  def self.most_caramel_points
    self.order(caramel_points: :desc).limit(10).pluck(:username)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    authorize_user
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @pet = Pet.new
  end

  def create
    @user = User.new(user_params)
    @user.username.downcase!
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_pet_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email, :name)
  end
end

app/views/users/new.html.erb
<section class="signup">
  
  <h1>new user</h1>
  <%= form_for(@user) do |f|%>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :username %>
  <%= f.text_field :username %><br>

  <%= f.label :password %>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>

  <%= f.label :email %>
  <%= f.text_field :email %><br>

  <%= f.submit %>
  <% end %>

</section>

app/views/users/show.html.erb
<body class="user">
  <section class="user-profile">
    <h1><%= @user.name%>'s Profile</h1>

    <p>username: <%= @user.username %></p>

    <p>my pet: <%= link_to "#{@user.pet.name}", pet_path(@user.pet) %></p>
  </section>

  <section class="user-pet-friends">
    <h2>my pet friends</h2>
    <ul>
    <% @user.pet_friends.each do |pet_friend| %>
    <li><%= link_to "#{pet_friend.name}", pet_path(pet_friend) %></li>
    <% end %>
    </ul>
  </section>

  <section class="caramels-display">
    <% if @user.caramel_points > 0 %>
      <%= @user.name %>'s caramel points: <br>
      <% @user.caramel_points.times do %>
        <div class='candy'>🍭</div>
      <% end %>
    <% end %>
  </section>
</body>